#ifndef _AFV_EVENTS_H__
#define _AFV_EVENTS_H__

#include "engine.h"

enum {
	EVENT_TYPE_STATUSLINE = ALLEGRO_GET_EVENT_TYPE('A', 'F', 'V', '1')
};

enum {
	EVENT_SYSTEM_LOG = 100,
	EVENT_SYSTEM_LOG_FATAL,
	EVENT_SYSTEM_LOG_ALERT,
	EVENT_SYSTEM_LOG_CRITICAL,
	EVENT_SYSTEM_LOG_ERROR,
	EVENT_SYSTEM_LOG_WARNING,
	EVENT_SYSTEM_LOG_NOTICE,
	EVENT_SYSTEM_LOG_INFO,
	EVENT_SYSTEM_LOG_DEBUG,
	EVENT_SYSTEM_LOG_TRACE
};

#endif /* _AFV_EVENTS_H__ */
